name: S3DeployStaging

on:
  push:
    branches: [ main ]

env:
  NODE_ENV: staging
  APP_TITLE: MS ALeRCE Explorer - Staging Build

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      id-token: write
      contents: read
    env:
      ALADIN_API_BASE_URL: ${{ secrets.ALADIN_API_BASE_URL }}
      CROSSMATCH_API_BASE_URL: ${{ secrets.CROSSMATCH_API_BASE_URL }}
      LIGHTCURVE_API_BASE_URL: ${{ secrets.LIGHTCURVE_API_BASE_URL }}
      MAGSTATS_API_BASE_URL: ${{ secrets.MAGSTATS_API_BASE_URL }}
      PROBABILITIES_API_BASE_URL: ${{ secrets.PROBABILITIES_API_BASE_URL }}
      OBJECT_API_BASE_URL: ${{ secrets.OBJECT_API_BASE_URL }}
      USERS_API_BASE_URL: ${{ secrets.USERS_API_BASE_URL }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_CLOUDFRONT: ${{ secrets.AWS_CLOUDFRONT_ID }}
      GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
    steps:
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1
          output-credentials: true
          unset-current-credentials: true
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install
      - run: npm run generate
      - run: npm run deploy
